### ISSUE TITLE
bug: long lasting connections terminate with sql error codes 

### ISSUE THREAD

**Issue by c-nv-s** [alash3al/redix#43]
during regular set/get:
``panic: FATAL: terminating connection due to idle-session timeout (SQLSTATE 57P05)``
``panic: FATAL: Terminated long-running connection (SQLSTATE 57000)``

during pub/sub:
``(error) ERR database::notification::err FATAL: terminating connection due to idle-session timeout (SQLSTATE 57P05)``

above sql error codes are received when redix is left idle for about 5-10 minutes and then a new command issued.
I think the default expected behaviour would be that it would naturally maintain the connection unless there was a config setting which you could determine how long to wait in idle before disconnecting.

tested with the stand-alone binary, not within a docker container.

**Comment by c-nv-s** [comment]
@alash3al is there any way around this error?

**Comment by alash3al** [comment]
I'm trying to re-produce locally, sorry for the late reply

**Comment by alash3al** [comment]
After some investigations and to simulate your state, I updated [idle_session_timeout](https://postgresqlco.nf/doc/en/param/idle_session_timeout/) from '0' the default value to '5000' ms and the problem happened.

It isn't related to redix itself, if you tried to LISTEN/NOTIFY on psql cli directly you will face the same problem because the connection is in an idle state, and PostgreSQL is configured to terminate the connection after 5000 ms, if I rolled it back to '0' everything would go fine.

**Comment by c-nv-s** [comment]
Hmm ok thanks i will check the setting to see if it was the problem

**Comment by c-nv-s** [comment]
turns out that ``idle_session_timeout`` setting is not available in postgres 13 so maybe you want to advise in the docs/README that there is a minimum version of postgres required.

edit: although I'm not seeing the error anymore and I've tested it in 13 + 14 so seems a bit strange but I'm happy to close this as resolved
